-- 基础规范号升级续执行脚本。
-- 适用于 upgrade_standard_documents_dm.sql 已成功执行建表、字段、外键和索引，
-- 但第 3 步迁移 INSERT 失败的情况。
-- 不要重复执行 CREATE TABLE、ALTER TABLE 和 CREATE INDEX。

-- 1. 生成基础规范号。
-- 先完成 GROUP BY，再在外层使用 ROW_NUMBER，避免达梦 -4080 “不是 GROUP BY 表达式”。
INSERT INTO CAD_SW_LIBRARY.STANDARD_DOCUMENTS
	(ID, FAMILY_ID, CATEGORY_ID, STANDARD_NUMBER, STANDARD_NAME, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT
	ROW_NUMBER() OVER (ORDER BY grouped_data.FAMILY_ID, grouped_data.STANDARD_NUMBER)
		+ COALESCE((SELECT MAX(ID) FROM CAD_SW_LIBRARY.STANDARD_DOCUMENTS), 0),
	grouped_data.FAMILY_ID,
	grouped_data.CATEGORY_ID,
	grouped_data.STANDARD_NUMBER,
	grouped_data.STANDARD_NUMBER,
	1,
	CURRENT_TIMESTAMP,
	CURRENT_TIMESTAMP
FROM (
	SELECT
		ss.FAMILY_ID,
		MIN(ss.CATEGORY_ID) AS CATEGORY_ID,
		TRIM(ss.STANDARD_NUMBER) AS STANDARD_NUMBER
	FROM CAD_SW_LIBRARY.STANDARD_SERIES ss
	WHERE ss.IS_ACTIVE = 1
	  AND TRIM(COALESCE(ss.STANDARD_NUMBER, '')) <> ''
	  AND NOT EXISTS (
		  SELECT 1
		  FROM CAD_SW_LIBRARY.STANDARD_DOCUMENTS sd
		  WHERE sd.FAMILY_ID = ss.FAMILY_ID
			AND sd.STANDARD_NUMBER = TRIM(ss.STANDARD_NUMBER)
	  )
	GROUP BY ss.FAMILY_ID, TRIM(ss.STANDARD_NUMBER)
) grouped_data;

-- 2. 将已有细分系列挂接到基础规范号。
UPDATE CAD_SW_LIBRARY.STANDARD_SERIES ss
SET STANDARD_DOCUMENT_ID = (
	SELECT sd.ID
	FROM CAD_SW_LIBRARY.STANDARD_DOCUMENTS sd
	WHERE sd.FAMILY_ID = ss.FAMILY_ID
	  AND sd.STANDARD_NUMBER = TRIM(ss.STANDARD_NUMBER)
	  AND sd.IS_ACTIVE = 1
)
WHERE ss.IS_ACTIVE = 1
  AND ss.STANDARD_DOCUMENT_ID IS NULL;

-- 3. 检查迁移结果。
SELECT COUNT(*) AS DOCUMENT_COUNT
FROM CAD_SW_LIBRARY.STANDARD_DOCUMENTS;

SELECT COUNT(*) AS UNLINKED_SERIES_COUNT
FROM CAD_SW_LIBRARY.STANDARD_SERIES
WHERE IS_ACTIVE = 1
  AND STANDARD_DOCUMENT_ID IS NULL;

SELECT sd.STANDARD_NUMBER, COUNT(ss.ID) AS SERIES_COUNT
FROM CAD_SW_LIBRARY.STANDARD_DOCUMENTS sd
LEFT JOIN CAD_SW_LIBRARY.STANDARD_SERIES ss
	ON ss.STANDARD_DOCUMENT_ID = sd.ID
   AND ss.IS_ACTIVE = 1
GROUP BY sd.STANDARD_NUMBER
ORDER BY sd.STANDARD_NUMBER;
