-- 检查基础规范号与细分规范树层级。
-- 目标库：CAD_SW_LIBRARY。

-- 1. 基础规范号。
SELECT
	ID,
	FAMILY_ID,
	CATEGORY_ID,
	STANDARD_NUMBER,
	STANDARD_NAME,
	IS_ACTIVE
FROM CAD_SW_LIBRARY.STANDARD_DOCUMENTS
ORDER BY STANDARD_NUMBER, ID;

-- 2. 基础规范号下的细分系列。
SELECT
	ss.ID AS SERIES_ID,
	ss.STANDARD_DOCUMENT_ID,
	sd.STANDARD_NUMBER AS BASE_STANDARD_NUMBER,
	ss.SERIES_NAME,
	ss.SERIES_CODE,
	ss.TABLE_NUMBER,
	ss.PRESSURE_RATING,
	ss.CATEGORY_ID,
	ss.IS_ACTIVE
FROM CAD_SW_LIBRARY.STANDARD_SERIES ss
LEFT JOIN CAD_SW_LIBRARY.STANDARD_DOCUMENTS sd
	ON sd.ID = ss.STANDARD_DOCUMENT_ID
ORDER BY sd.STANDARD_NUMBER, ss.SERIES_NAME, ss.TABLE_NUMBER, ss.PRESSURE_RATING, ss.ID;

-- 3. 细分系列下的动态版本。
SELECT
	v.ID AS VERSION_ID,
	v.SERIES_ID,
	sd.STANDARD_NUMBER AS BASE_STANDARD_NUMBER,
	ss.SERIES_NAME,
	ss.TABLE_NUMBER,
	ss.PRESSURE_RATING,
	v.VERSION_NO,
	v.VERSION_LABEL,
	v.SOURCE_TYPE,
	v.IS_CURRENT,
	v.IS_DELETED
FROM CAD_SW_LIBRARY.STANDARD_DOCUMENT_VERSIONS v
INNER JOIN CAD_SW_LIBRARY.STANDARD_SERIES ss
	ON ss.ID = v.SERIES_ID
LEFT JOIN CAD_SW_LIBRARY.STANDARD_DOCUMENTS sd
	ON sd.ID = ss.STANDARD_DOCUMENT_ID
ORDER BY sd.STANDARD_NUMBER, ss.SERIES_NAME, v.ID;

-- 4. 直接查看当前期望层级。
SELECT
	sd.STANDARD_NUMBER AS 基础规范号,
	ss.SERIES_NAME AS 细分规范名称,
	ss.TABLE_NUMBER AS 表号,
	ss.PRESSURE_RATING AS 型号,
	v.VERSION_LABEL AS 动态版本
FROM CAD_SW_LIBRARY.STANDARD_DOCUMENTS sd
INNER JOIN CAD_SW_LIBRARY.STANDARD_SERIES ss
	ON ss.STANDARD_DOCUMENT_ID = sd.ID
LEFT JOIN CAD_SW_LIBRARY.STANDARD_DOCUMENT_VERSIONS v
	ON v.SERIES_ID = ss.ID
   AND v.IS_CURRENT = 1
   AND v.IS_DELETED = 0
ORDER BY sd.STANDARD_NUMBER, ss.SERIES_NAME, ss.TABLE_NUMBER, ss.PRESSURE_RATING;
