-- 规范库 DM 结构核验脚本
-- 用途：重建后确认表、字段、约束、索引和数据量是否符合预期。
-- 本脚本只查询，不修改任何数据或结构。

-- 一、确认规范库表是否全部存在。
SELECT OWNER, TABLE_NAME
FROM ALL_TABLES
WHERE OWNER = 'CAD_SW_LIBRARY'
  AND TABLE_NAME IN (
	'STANDARD_FAMILIES',
	'STANDARD_SERIES',
	'STANDARD_FLANGE_RECORDS',
	'STANDARD_CATEGORIES',
	'STANDARD_DOCUMENT_VERSIONS',
	'STANDARD_DOCUMENT_FILES',
	'STANDARD_OPERATION_LOGS',
	'STANDARD_TEMPLATES',
	'STANDARD_TEMPLATE_COLUMNS',
	'STANDARD_IMPORT_BATCHES',
	'STANDARD_IMPORT_ROWS',
	'STANDARD_DYNAMIC_VERSION_ROWS'
  )
ORDER BY TABLE_NAME;

-- 二、查看规范表之间的外键关系。
SELECT
	C.OWNER,
	C.TABLE_NAME,
	C.CONSTRAINT_NAME,
	C.CONSTRAINT_TYPE,
	C.R_CONSTRAINT_NAME,
	RC.TABLE_NAME AS REFERENCED_TABLE_NAME,
	C.STATUS
FROM ALL_CONSTRAINTS C
LEFT JOIN ALL_CONSTRAINTS RC
	ON RC.OWNER = C.R_OWNER
   AND RC.CONSTRAINT_NAME = C.R_CONSTRAINT_NAME
WHERE C.OWNER = 'CAD_SW_LIBRARY'
  AND (
	   C.TABLE_NAME LIKE 'STANDARD_%'
	   OR RC.TABLE_NAME LIKE 'STANDARD_%'
  )
ORDER BY C.TABLE_NAME, C.CONSTRAINT_NAME;

-- 三、查看规范表字段，确认重建脚本没有缺字段。
SELECT OWNER, TABLE_NAME, COLUMN_ID, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'CAD_SW_LIBRARY'
  AND TABLE_NAME LIKE 'STANDARD_%'
ORDER BY TABLE_NAME, COLUMN_ID;

-- 四、查看规范表索引和唯一索引。
SELECT OWNER, TABLE_NAME, INDEX_NAME, INDEX_TYPE, UNIQUENESS, STATUS
FROM ALL_INDEXES
WHERE OWNER = 'CAD_SW_LIBRARY'
  AND TABLE_NAME LIKE 'STANDARD_%'
ORDER BY TABLE_NAME, INDEX_NAME;

-- 五、查看主要业务表数据量；刚重建后这些数量应全部为 0。
SELECT 'STANDARD_FAMILIES' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CAD_SW_LIBRARY.STANDARD_FAMILIES
UNION ALL
SELECT 'STANDARD_SERIES', COUNT(*) FROM CAD_SW_LIBRARY.STANDARD_SERIES
UNION ALL
SELECT 'STANDARD_FLANGE_RECORDS', COUNT(*) FROM CAD_SW_LIBRARY.STANDARD_FLANGE_RECORDS
UNION ALL
SELECT 'STANDARD_CATEGORIES', COUNT(*) FROM CAD_SW_LIBRARY.STANDARD_CATEGORIES
UNION ALL
SELECT 'STANDARD_DOCUMENT_VERSIONS', COUNT(*) FROM CAD_SW_LIBRARY.STANDARD_DOCUMENT_VERSIONS
UNION ALL
SELECT 'STANDARD_DOCUMENT_FILES', COUNT(*) FROM CAD_SW_LIBRARY.STANDARD_DOCUMENT_FILES
UNION ALL
SELECT 'STANDARD_OPERATION_LOGS', COUNT(*) FROM CAD_SW_LIBRARY.STANDARD_OPERATION_LOGS
UNION ALL
SELECT 'STANDARD_TEMPLATES', COUNT(*) FROM CAD_SW_LIBRARY.STANDARD_TEMPLATES
UNION ALL
SELECT 'STANDARD_TEMPLATE_COLUMNS', COUNT(*) FROM CAD_SW_LIBRARY.STANDARD_TEMPLATE_COLUMNS
UNION ALL
SELECT 'STANDARD_IMPORT_BATCHES', COUNT(*) FROM CAD_SW_LIBRARY.STANDARD_IMPORT_BATCHES
UNION ALL
SELECT 'STANDARD_IMPORT_ROWS', COUNT(*) FROM CAD_SW_LIBRARY.STANDARD_IMPORT_ROWS
UNION ALL
SELECT 'STANDARD_DYNAMIC_VERSION_ROWS', COUNT(*) FROM CAD_SW_LIBRARY.STANDARD_DYNAMIC_VERSION_ROWS;

-- 六、确认不应保留旧归并临时表；正常结果应为空。
SELECT OWNER, TABLE_NAME
FROM ALL_TABLES
WHERE OWNER = 'CAD_SW_LIBRARY'
  AND TABLE_NAME IN (
	'STANDARD_MERGE_SERIES_IDS',
	'STANDARD_MERGE_VERSION_IDS',
	'STANDARD_MERGE_BATCH_IDS',
	'STANDARD_MERGE_TEMPLATE_IDS'
  )
ORDER BY TABLE_NAME;
