-- 动态规范系列归并并重置：达梦版本
-- 目标示例：板式平焊钢制管法兰 + GB/T 9124.1-2019
-- 执行前必须备份 CAD_SW_LIBRARY；脚本只生成/检查，不由客户端自动执行。
-- 如果目标名称或标准号不同，请修改下面两个变量。

DECLARE
	V_BASE_NAME VARCHAR(255) := '板式平焊钢制管法兰';
	V_BASE_STANDARD VARCHAR(100) := 'GB/T 9124.1-2019';
	V_BASE_SERIES_ID BIGINT;
	V_FAMILY_ID BIGINT;
	V_CATEGORY_ID BIGINT;
	V_NEW_ID BIGINT;
	V_NEW_CODE VARCHAR(100);
	V_COUNT BIGINT;
BEGIN
	EXECUTE IMMEDIATE 'TRUNCATE TABLE CAD_SW_LIBRARY.STANDARD_MERGE_SERIES_IDS';
EXCEPTION
	WHEN OTHERS THEN NULL;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE CAD_SW_LIBRARY.STANDARD_MERGE_SERIES_IDS (ID BIGINT PRIMARY KEY) ON COMMIT PRESERVE ROWS';
EXCEPTION
	WHEN OTHERS THEN NULL;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE CAD_SW_LIBRARY.STANDARD_MERGE_VERSION_IDS (ID BIGINT PRIMARY KEY) ON COMMIT PRESERVE ROWS';
EXCEPTION
	WHEN OTHERS THEN NULL;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE CAD_SW_LIBRARY.STANDARD_MERGE_BATCH_IDS (BATCH_ID VARCHAR(32) PRIMARY KEY) ON COMMIT PRESERVE ROWS';
EXCEPTION
	WHEN OTHERS THEN NULL;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE CAD_SW_LIBRARY.STANDARD_MERGE_TEMPLATE_IDS (ID BIGINT PRIMARY KEY) ON COMMIT PRESERVE ROWS';
EXCEPTION
	WHEN OTHERS THEN NULL;
END;
/

DECLARE
	V_BASE_NAME VARCHAR(255) := '板式平焊钢制管法兰';
	V_BASE_STANDARD VARCHAR(100) := 'GB/T 9124.1-2019';
	V_BASE_SERIES_ID BIGINT;
	V_FAMILY_ID BIGINT;
	V_CATEGORY_ID BIGINT;
	V_NEW_ID BIGINT;
	V_NEW_CODE VARCHAR(100);
	V_COUNT BIGINT;
BEGIN
	INSERT INTO CAD_SW_LIBRARY.STANDARD_MERGE_SERIES_IDS (ID)
	SELECT ID
	FROM CAD_SW_LIBRARY.STANDARD_SERIES
	WHERE IS_ACTIVE = 1
	  AND UPPER(TRIM(STANDARD_NUMBER)) = UPPER(TRIM(V_BASE_STANDARD))
	  AND UPPER(TRIM(SERIES_NAME)) LIKE UPPER(TRIM(V_BASE_NAME)) || '%';

	SELECT COUNT(DISTINCT NVL(CATEGORY_ID, 0)) INTO V_COUNT
	FROM CAD_SW_LIBRARY.STANDARD_SERIES S
	JOIN CAD_SW_LIBRARY.STANDARD_MERGE_SERIES_IDS X ON X.ID = S.ID;
	IF V_COUNT > 1 THEN
		RAISE_APPLICATION_ERROR(-20001, '目标规范系列跨多个分类，请先人工确认 CATEGORY_ID。');
	END IF;

	SELECT MIN(ID) INTO V_BASE_SERIES_ID
	FROM CAD_SW_LIBRARY.STANDARD_SERIES
	WHERE IS_ACTIVE = 1
	  AND UPPER(TRIM(SERIES_NAME)) = UPPER(TRIM(V_BASE_NAME))
	  AND UPPER(TRIM(STANDARD_NUMBER)) = UPPER(TRIM(V_BASE_STANDARD));

	SELECT MIN(FAMILY_ID), MIN(CATEGORY_ID) INTO V_FAMILY_ID, V_CATEGORY_ID
	FROM CAD_SW_LIBRARY.STANDARD_SERIES S
	JOIN CAD_SW_LIBRARY.STANDARD_MERGE_SERIES_IDS X ON X.ID = S.ID;

	IF V_BASE_SERIES_ID IS NULL THEN
		SELECT NVL(MAX(ID), 0) + 1 INTO V_NEW_ID FROM CAD_SW_LIBRARY.STANDARD_SERIES;
		V_NEW_CODE := 'DYNAMIC-' || REPLACE(REPLACE(UPPER(V_BASE_STANDARD), '/', '-'), ' ', '');
		INSERT INTO CAD_SW_LIBRARY.STANDARD_SERIES
			(ID, FAMILY_ID, CATEGORY_ID, SERIES_CODE, SERIES_NAME, STANDARD_NUMBER,
			 TABLE_NUMBER, PRESSURE_RATING, FLANGE_TYPE, FACE_TYPE, IS_ACTIVE, CREATED_AT, UPDATED_AT)
		VALUES
			(V_NEW_ID, V_FAMILY_ID, V_CATEGORY_ID, V_NEW_CODE, V_BASE_NAME, V_BASE_STANDARD,
			 '', '', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
		V_BASE_SERIES_ID := V_NEW_ID;
	END IF;

	INSERT INTO CAD_SW_LIBRARY.STANDARD_MERGE_SERIES_IDS (ID)
	SELECT V_BASE_SERIES_ID FROM DUAL
	WHERE NOT EXISTS (SELECT 1 FROM CAD_SW_LIBRARY.STANDARD_MERGE_SERIES_IDS WHERE ID = V_BASE_SERIES_ID);

	DELETE FROM CAD_SW_LIBRARY.STANDARD_MERGE_VERSION_IDS;
	INSERT INTO CAD_SW_LIBRARY.STANDARD_MERGE_VERSION_IDS (ID)
	SELECT ID FROM CAD_SW_LIBRARY.STANDARD_DOCUMENT_VERSIONS
	WHERE SERIES_ID IN (SELECT ID FROM CAD_SW_LIBRARY.STANDARD_MERGE_SERIES_IDS);

	DELETE FROM CAD_SW_LIBRARY.STANDARD_MERGE_BATCH_IDS;
	INSERT INTO CAD_SW_LIBRARY.STANDARD_MERGE_BATCH_IDS (BATCH_ID)
	SELECT BATCH_ID FROM CAD_SW_LIBRARY.STANDARD_IMPORT_BATCHES
	WHERE SERIES_ID IN (SELECT ID FROM CAD_SW_LIBRARY.STANDARD_MERGE_SERIES_IDS);

	DELETE FROM CAD_SW_LIBRARY.STANDARD_MERGE_TEMPLATE_IDS;
	INSERT INTO CAD_SW_LIBRARY.STANDARD_MERGE_TEMPLATE_IDS (ID)
	SELECT TEMPLATE_ID FROM CAD_SW_LIBRARY.STANDARD_IMPORT_BATCHES
	WHERE TEMPLATE_ID IS NOT NULL
		AND BATCH_ID IN (SELECT BATCH_ID FROM CAD_SW_LIBRARY.STANDARD_MERGE_BATCH_IDS)
	  AND NOT EXISTS (
		  SELECT 1 FROM CAD_SW_LIBRARY.STANDARD_IMPORT_BATCHES B2
		  WHERE B2.TEMPLATE_ID = STANDARD_IMPORT_BATCHES.TEMPLATE_ID
			AND B2.BATCH_ID NOT IN (SELECT BATCH_ID FROM CAD_SW_LIBRARY.STANDARD_MERGE_BATCH_IDS)
	  );

	DELETE FROM CAD_SW_LIBRARY.STANDARD_DOCUMENT_FILES
	WHERE VERSION_ID IN (SELECT ID FROM CAD_SW_LIBRARY.STANDARD_MERGE_VERSION_IDS);
	DELETE FROM CAD_SW_LIBRARY.STANDARD_DYNAMIC_VERSION_ROWS
	WHERE VERSION_ID IN (SELECT ID FROM CAD_SW_LIBRARY.STANDARD_MERGE_VERSION_IDS);
	DELETE FROM CAD_SW_LIBRARY.STANDARD_IMPORT_ROWS
	WHERE BATCH_ID IN (SELECT BATCH_ID FROM CAD_SW_LIBRARY.STANDARD_MERGE_BATCH_IDS);
	DELETE FROM CAD_SW_LIBRARY.STANDARD_OPERATION_LOGS
	WHERE SERIES_ID IN (SELECT ID FROM CAD_SW_LIBRARY.STANDARD_MERGE_SERIES_IDS)
	   OR VERSION_ID IN (SELECT ID FROM CAD_SW_LIBRARY.STANDARD_MERGE_VERSION_IDS);
	DELETE FROM CAD_SW_LIBRARY.STANDARD_IMPORT_BATCHES
	WHERE BATCH_ID IN (SELECT BATCH_ID FROM CAD_SW_LIBRARY.STANDARD_MERGE_BATCH_IDS);
	DELETE FROM CAD_SW_LIBRARY.STANDARD_DOCUMENT_VERSIONS
	WHERE ID IN (SELECT ID FROM CAD_SW_LIBRARY.STANDARD_MERGE_VERSION_IDS);
	DELETE FROM CAD_SW_LIBRARY.STANDARD_TEMPLATE_COLUMNS
	WHERE TEMPLATE_ID IN (SELECT ID FROM CAD_SW_LIBRARY.STANDARD_MERGE_TEMPLATE_IDS)
	  AND NOT EXISTS (
		  SELECT 1 FROM CAD_SW_LIBRARY.STANDARD_IMPORT_BATCHES B
		  WHERE B.TEMPLATE_ID = STANDARD_TEMPLATE_COLUMNS.TEMPLATE_ID
	  );
	DELETE FROM CAD_SW_LIBRARY.STANDARD_TEMPLATES
	WHERE ID IN (SELECT ID FROM CAD_SW_LIBRARY.STANDARD_MERGE_TEMPLATE_IDS)
	  AND NOT EXISTS (
		  SELECT 1 FROM CAD_SW_LIBRARY.STANDARD_IMPORT_BATCHES B
		  WHERE B.TEMPLATE_ID = STANDARD_TEMPLATES.ID
	  );
	DELETE FROM CAD_SW_LIBRARY.STANDARD_FLANGE_RECORDS
	WHERE SERIES_ID IN (SELECT ID FROM CAD_SW_LIBRARY.STANDARD_MERGE_SERIES_IDS);

	UPDATE CAD_SW_LIBRARY.STANDARD_SERIES
	SET IS_ACTIVE = CASE WHEN ID = V_BASE_SERIES_ID THEN 1 ELSE 0 END,
		UPDATED_AT = CURRENT_TIMESTAMP
	WHERE ID IN (SELECT ID FROM CAD_SW_LIBRARY.STANDARD_MERGE_SERIES_IDS);

	UPDATE CAD_SW_LIBRARY.STANDARD_SERIES
	SET SERIES_NAME = V_BASE_NAME,
		STANDARD_NUMBER = V_BASE_STANDARD,
		TABLE_NUMBER = '',
		PRESSURE_RATING = '',
		UPDATED_AT = CURRENT_TIMESTAMP
	WHERE ID = V_BASE_SERIES_ID;

	COMMIT;
	SELECT ID, CATEGORY_ID, FAMILY_ID, SERIES_CODE, SERIES_NAME, STANDARD_NUMBER,
		   TABLE_NUMBER, PRESSURE_RATING, IS_ACTIVE
	FROM CAD_SW_LIBRARY.STANDARD_SERIES
	WHERE ID = V_BASE_SERIES_ID
	   OR (UPPER(TRIM(STANDARD_NUMBER)) = UPPER(TRIM(V_BASE_STANDARD))
		   AND UPPER(TRIM(SERIES_NAME)) LIKE UPPER(TRIM(V_BASE_NAME)) || '%')
	ORDER BY ID;
END;
/

