-- 将规范库从 SYSDBA 迁移到 CAD_SW_LIBRARY。
-- 执行前确认：
-- 1. CAD_SW_LIBRARY schema 已存在；
-- 2. 当前账号具备在 CAD_SW_LIBRARY 下创建表、约束、索引和写入数据的权限；
-- 3. 目标表尚未存在；
-- 4. 已备份 SYSDBA 下的源表。
-- 本脚本不会删除 SYSDBA 下的源表。

CREATE TABLE CAD_SW_LIBRARY.STANDARD_FAMILIES (
	ID BIGINT NOT NULL,
	CODE VARCHAR(64) NOT NULL,
	NAME VARCHAR(128) NOT NULL,
	DESCRIPTION VARCHAR(500),
	IS_ACTIVE INT DEFAULT 1 NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_STANDARD_FAMILIES PRIMARY KEY (ID),
	CONSTRAINT UK_STANDARD_FAMILIES_CODE UNIQUE (CODE)
);

CREATE TABLE CAD_SW_LIBRARY.STANDARD_SERIES (
	ID BIGINT NOT NULL,
	FAMILY_ID BIGINT NOT NULL,
	SERIES_CODE VARCHAR(100) NOT NULL,
	SERIES_NAME VARCHAR(255) NOT NULL,
	STANDARD_NUMBER VARCHAR(100) NOT NULL,
	TABLE_NUMBER VARCHAR(64) NOT NULL,
	PRESSURE_RATING VARCHAR(64) NOT NULL,
	FLANGE_TYPE VARCHAR(64),
	FACE_TYPE VARCHAR(64),
	IS_ACTIVE INT DEFAULT 1 NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_STANDARD_SERIES PRIMARY KEY (ID),
	CONSTRAINT UK_STANDARD_SERIES_IDENTITY UNIQUE
		(FAMILY_ID, SERIES_CODE, STANDARD_NUMBER, TABLE_NUMBER, PRESSURE_RATING)
);

CREATE TABLE CAD_SW_LIBRARY.STANDARD_FLANGE_RECORDS (
	ID BIGINT NOT NULL,
	SERIES_ID BIGINT NOT NULL,
	SOURCE_ROW_NUMBER INT NOT NULL,
	DN VARCHAR(32) NOT NULL,
	DN_VALUE INT NOT NULL,
	PN VARCHAR(64) NOT NULL,
	PIPE_OUTER_DIAMETER_I DECIMAL(18,4),
	PIPE_OUTER_DIAMETER_II DECIMAL(18,4),
	FLANGE_OUTER_DIAMETER DECIMAL(18,4),
	BOLT_CIRCLE_DIAMETER DECIMAL(18,4),
	BOLT_HOLE_DIAMETER DECIMAL(18,4),
	BOLT_COUNT INT,
	BOLT_SPECIFICATION VARCHAR(64),
	BOLT_RAW_SUFFIX VARCHAR(128),
	FLANGE_THICKNESS DECIMAL(18,4),
	RAISED_FACE_HEIGHT DECIMAL(18,4),
	FLANGE_INNER_DIAMETER_I DECIMAL(18,4),
	FLANGE_INNER_DIAMETER_II DECIMAL(18,4),
	RAW_VALUES_JSON TEXT,
	WARNINGS_JSON TEXT,
	IS_ACTIVE INT DEFAULT 1 NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_STANDARD_FLANGE_RECORDS PRIMARY KEY (ID),
	CONSTRAINT UK_STANDARD_FLANGE_RECORD_IDENTITY UNIQUE (SERIES_ID, DN_VALUE, PN)
);

INSERT INTO CAD_SW_LIBRARY.STANDARD_FAMILIES
	(ID, CODE, NAME, DESCRIPTION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT
	ID, CODE, NAME, DESCRIPTION, IS_ACTIVE, CREATED_AT, UPDATED_AT
FROM SYSDBA.STANDARD_FAMILIES;

INSERT INTO CAD_SW_LIBRARY.STANDARD_SERIES
	(ID, FAMILY_ID, SERIES_CODE, SERIES_NAME, STANDARD_NUMBER, TABLE_NUMBER,
	 PRESSURE_RATING, FLANGE_TYPE, FACE_TYPE, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT
	ID, FAMILY_ID, SERIES_CODE, SERIES_NAME, STANDARD_NUMBER, TABLE_NUMBER,
	PRESSURE_RATING, FLANGE_TYPE, FACE_TYPE, IS_ACTIVE, CREATED_AT, UPDATED_AT
FROM SYSDBA.STANDARD_SERIES;

INSERT INTO CAD_SW_LIBRARY.STANDARD_FLANGE_RECORDS
	(ID, SERIES_ID, SOURCE_ROW_NUMBER, DN, DN_VALUE, PN,
	 PIPE_OUTER_DIAMETER_I, PIPE_OUTER_DIAMETER_II, FLANGE_OUTER_DIAMETER,
	 BOLT_CIRCLE_DIAMETER, BOLT_HOLE_DIAMETER, BOLT_COUNT, BOLT_SPECIFICATION,
	 BOLT_RAW_SUFFIX, FLANGE_THICKNESS, RAISED_FACE_HEIGHT,
	 FLANGE_INNER_DIAMETER_I, FLANGE_INNER_DIAMETER_II, RAW_VALUES_JSON,
	 WARNINGS_JSON, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT
	ID, SERIES_ID, SOURCE_ROW_NUMBER, DN, DN_VALUE, PN,
	PIPE_OUTER_DIAMETER_I, PIPE_OUTER_DIAMETER_II, FLANGE_OUTER_DIAMETER,
	BOLT_CIRCLE_DIAMETER, BOLT_HOLE_DIAMETER, BOLT_COUNT, BOLT_SPECIFICATION,
	BOLT_RAW_SUFFIX, FLANGE_THICKNESS, RAISED_FACE_HEIGHT,
	FLANGE_INNER_DIAMETER_I, FLANGE_INNER_DIAMETER_II, RAW_VALUES_JSON,
	WARNINGS_JSON, IS_ACTIVE, CREATED_AT, UPDATED_AT
FROM SYSDBA.STANDARD_FLANGE_RECORDS;

CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_SERIES_QUERY
	ON CAD_SW_LIBRARY.STANDARD_SERIES (SERIES_CODE, STANDARD_NUMBER, PRESSURE_RATING);

CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_FLANGE_RECORD_QUERY
	ON CAD_SW_LIBRARY.STANDARD_FLANGE_RECORDS (SERIES_ID, DN_VALUE, PN);

-- 迁移完成后校验三张表的行数应一致。
SELECT 'STANDARD_FAMILIES' AS TABLE_NAME,
	   (SELECT COUNT(*) FROM SYSDBA.STANDARD_FAMILIES) AS SOURCE_COUNT,
	   (SELECT COUNT(*) FROM CAD_SW_LIBRARY.STANDARD_FAMILIES) AS TARGET_COUNT
FROM DUAL;

SELECT 'STANDARD_SERIES' AS TABLE_NAME,
	   (SELECT COUNT(*) FROM SYSDBA.STANDARD_SERIES) AS SOURCE_COUNT,
	   (SELECT COUNT(*) FROM CAD_SW_LIBRARY.STANDARD_SERIES) AS TARGET_COUNT
FROM DUAL;

SELECT 'STANDARD_FLANGE_RECORDS' AS TABLE_NAME,
	   (SELECT COUNT(*) FROM SYSDBA.STANDARD_FLANGE_RECORDS) AS SOURCE_COUNT,
	   (SELECT COUNT(*) FROM CAD_SW_LIBRARY.STANDARD_FLANGE_RECORDS) AS TARGET_COUNT
FROM DUAL;
