-- 规范导入模板与批次：达梦版本
-- 对象统一创建到服务配置中的 Database:Schema（默认 CAD_SW_LIBRARY）。

CREATE TABLE CAD_SW_LIBRARY.STANDARD_TEMPLATES (
	ID BIGINT NOT NULL,
	TEMPLATE_CODE VARCHAR(128) NOT NULL,
	TEMPLATE_NAME VARCHAR(255) NOT NULL,
	FAMILY_CODE VARCHAR(64) NOT NULL,
	FILE_TYPE VARCHAR(16) DEFAULT 'XLSX' NOT NULL,
	VERSION INT DEFAULT 1 NOT NULL,
	IS_ACTIVE INT DEFAULT 1 NOT NULL,
	DESCRIPTION VARCHAR(1000),
	CREATED_BY VARCHAR(128),
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_STANDARD_TEMPLATES PRIMARY KEY (ID),
	CONSTRAINT UK_STANDARD_TEMPLATES_CODE_VERSION UNIQUE (TEMPLATE_CODE, VERSION)
);

CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_TEMPLATES_FAMILY
	ON CAD_SW_LIBRARY.STANDARD_TEMPLATES (FAMILY_CODE, IS_ACTIVE);

CREATE TABLE CAD_SW_LIBRARY.STANDARD_TEMPLATE_COLUMNS (
	ID BIGINT NOT NULL,
	TEMPLATE_ID BIGINT NOT NULL,
	FIELD_CODE VARCHAR(128) NOT NULL,
	FIELD_NAME VARCHAR(255) NOT NULL,
	DATA_TYPE VARCHAR(32) DEFAULT 'TEXT' NOT NULL,
	UNIT VARCHAR(32),
	IS_REQUIRED INT DEFAULT 0 NOT NULL,
	SORT_ORDER INT DEFAULT 0 NOT NULL,
	HEADER_ALIASES_JSON TEXT,
	VALIDATION_JSON TEXT,
	CONSTRAINT PK_STANDARD_TEMPLATE_COLUMNS PRIMARY KEY (ID),
	CONSTRAINT UK_STANDARD_TEMPLATE_COLUMNS_FIELD UNIQUE (TEMPLATE_ID, FIELD_CODE),
	CONSTRAINT FK_STANDARD_TEMPLATE_COLUMNS_TEMPLATE FOREIGN KEY (TEMPLATE_ID)
		REFERENCES CAD_SW_LIBRARY.STANDARD_TEMPLATES(ID)
);

CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_TEMPLATE_COLUMNS_ORDER
	ON CAD_SW_LIBRARY.STANDARD_TEMPLATE_COLUMNS (TEMPLATE_ID, SORT_ORDER);

CREATE TABLE CAD_SW_LIBRARY.STANDARD_IMPORT_BATCHES (
	BATCH_ID VARCHAR(32) NOT NULL,
	SERIES_ID BIGINT NOT NULL,
	VERSION_ID BIGINT,
	TEMPLATE_ID BIGINT,
	FAMILY_CODE VARCHAR(64) NOT NULL,
	STATUS VARCHAR(32) DEFAULT 'PREVIEW' NOT NULL,
	ROW_COUNT INT DEFAULT 0 NOT NULL,
	ERROR_COUNT INT DEFAULT 0 NOT NULL,
	WARNING_COUNT INT DEFAULT 0 NOT NULL,
	SOURCE_FILE_NAME VARCHAR(255),
	SOURCE_FILE_SHA256 VARCHAR(64),
	CREATED_BY VARCHAR(128),
	CREATED_AT TIMESTAMP NOT NULL,
	EXPIRES_AT TIMESTAMP,
	CONSTRAINT PK_STANDARD_IMPORT_BATCHES PRIMARY KEY (BATCH_ID),
	CONSTRAINT FK_STANDARD_IMPORT_BATCHES_SERIES FOREIGN KEY (SERIES_ID)
		REFERENCES CAD_SW_LIBRARY.STANDARD_SERIES(ID),
	CONSTRAINT FK_STANDARD_IMPORT_BATCHES_TEMPLATE FOREIGN KEY (TEMPLATE_ID)
		REFERENCES CAD_SW_LIBRARY.STANDARD_TEMPLATES(ID)
);

CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_IMPORT_BATCHES_STATUS
	ON CAD_SW_LIBRARY.STANDARD_IMPORT_BATCHES (STATUS, EXPIRES_AT);
