-- GB 设计规范资料管理扩展：达梦版本。
-- 固定目标库/Schema：CAD_SW_LIBRARY。
-- 本文件中的每一张表、约束和索引均使用 CAD_SW_LIBRARY 全限定名称。
-- 本脚本依赖 standard_schema_dm.sql 已经成功执行。

CREATE TABLE CAD_SW_LIBRARY.STANDARD_CATEGORIES (
	ID BIGINT NOT NULL,
	PARENT_ID BIGINT,
	CODE VARCHAR(100) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(500),
	SORT_ORDER INT DEFAULT 0 NOT NULL,
	IS_ACTIVE INT DEFAULT 1 NOT NULL,
	CREATED_BY VARCHAR(128),
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_STANDARD_CATEGORIES PRIMARY KEY (ID),
	CONSTRAINT UK_STANDARD_CATEGORIES_PARENT_CODE UNIQUE (PARENT_ID, CODE)
);

CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_CATEGORIES_PARENT
	ON CAD_SW_LIBRARY.STANDARD_CATEGORIES (PARENT_ID, IS_ACTIVE);

-- 将现有规范系列挂接到专业/类别目录；为空时兼容历史数据。
ALTER TABLE CAD_SW_LIBRARY.STANDARD_SERIES ADD CATEGORY_ID BIGINT;
CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_SERIES_CATEGORY
	ON CAD_SW_LIBRARY.STANDARD_SERIES (CATEGORY_ID, IS_ACTIVE);

CREATE TABLE CAD_SW_LIBRARY.STANDARD_DOCUMENT_VERSIONS (
	ID BIGINT NOT NULL,
	SERIES_ID BIGINT NOT NULL,
	VERSION_NO VARCHAR(64) NOT NULL,
	VERSION_LABEL VARCHAR(128),
	CHANGE_SUMMARY VARCHAR(1000),
	SOURCE_TYPE VARCHAR(32) NOT NULL,
	STATUS VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL,
	IS_CURRENT INT DEFAULT 0 NOT NULL,
	IS_DELETED INT DEFAULT 0 NOT NULL,
	CREATED_BY VARCHAR(128),
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_STANDARD_DOCUMENT_VERSIONS PRIMARY KEY (ID),
	CONSTRAINT UK_STANDARD_DOCUMENT_VERSIONS_SERIES_VERSION UNIQUE (SERIES_ID, VERSION_NO),
	CONSTRAINT FK_STANDARD_DOCUMENT_VERSIONS_SERIES FOREIGN KEY (SERIES_ID)
		REFERENCES CAD_SW_LIBRARY.STANDARD_SERIES(ID)
);

CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_DOCUMENT_VERSIONS_CURRENT
	ON CAD_SW_LIBRARY.STANDARD_DOCUMENT_VERSIONS (SERIES_ID, IS_CURRENT, IS_DELETED);

CREATE TABLE CAD_SW_LIBRARY.STANDARD_DOCUMENT_FILES (
	ID BIGINT NOT NULL,
	VERSION_ID BIGINT NOT NULL,
	FILE_ROLE VARCHAR(32) DEFAULT 'MAIN' NOT NULL,
	ORIGINAL_FILE_NAME VARCHAR(255) NOT NULL,
	STORED_FILE_NAME VARCHAR(255) NOT NULL,
	RELATIVE_PATH VARCHAR(1000) NOT NULL,
	EXTENSION VARCHAR(32) NOT NULL,
	CONTENT_TYPE VARCHAR(255),
	FILE_SIZE BIGINT NOT NULL,
	SHA256 VARCHAR(64) NOT NULL,
	DESCRIPTION VARCHAR(1000),
	IS_DELETED INT DEFAULT 0 NOT NULL,
	CREATED_BY VARCHAR(128),
	CREATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_STANDARD_DOCUMENT_FILES PRIMARY KEY (ID),
	CONSTRAINT FK_STANDARD_DOCUMENT_FILES_VERSION FOREIGN KEY (VERSION_ID)
		REFERENCES CAD_SW_LIBRARY.STANDARD_DOCUMENT_VERSIONS(ID)
);

CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_DOCUMENT_FILES_VERSION
	ON CAD_SW_LIBRARY.STANDARD_DOCUMENT_FILES (VERSION_ID, IS_DELETED);
CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_DOCUMENT_FILES_HASH
	ON CAD_SW_LIBRARY.STANDARD_DOCUMENT_FILES (SHA256);

CREATE TABLE CAD_SW_LIBRARY.STANDARD_OPERATION_LOGS (
	ID BIGINT NOT NULL,
	OPERATION_TYPE VARCHAR(64) NOT NULL,
	CATEGORY_ID BIGINT,
	SERIES_ID BIGINT,
	VERSION_ID BIGINT,
	FILE_ID BIGINT,
	OPERATOR_NAME VARCHAR(128),
	DETAIL_JSON TEXT,
	CREATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_STANDARD_OPERATION_LOGS PRIMARY KEY (ID)
);

CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_OPERATION_LOGS_CREATED_AT
	ON CAD_SW_LIBRARY.STANDARD_OPERATION_LOGS (CREATED_AT);
CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_OPERATION_LOGS_TARGET
	ON CAD_SW_LIBRARY.STANDARD_OPERATION_LOGS (SERIES_ID, VERSION_ID);
