-- 规范导入模板与动态导入批次：达梦版本。
-- 固定目标库/Schema：CAD_SW_LIBRARY。
-- 本文件中的每一张表、约束和索引均使用 CAD_SW_LIBRARY 全限定名称。
-- 执行顺序：模板主表 -> 模板字段表 -> 导入批次表 -> 动态版本行表 -> 导入行表。
-- 本脚本依赖 standard_schema_dm.sql 和 standard_management_schema_dm.sql 已经成功执行。

CREATE TABLE CAD_SW_LIBRARY.STANDARD_TEMPLATES (
	ID BIGINT NOT NULL,
	TEMPLATE_CODE VARCHAR(128) NOT NULL,
	TEMPLATE_NAME VARCHAR(255) NOT NULL,
	FAMILY_CODE VARCHAR(64) NOT NULL,
	FILE_TYPE VARCHAR(16) DEFAULT 'XLSX' NOT NULL,
	TEMPLATE_VERSION INT DEFAULT 1 NOT NULL,
	IS_ACTIVE INT DEFAULT 1 NOT NULL,
	DESCRIPTION VARCHAR(1000),
	SOURCE_FILE_NAME VARCHAR(255),
	UNIQUE_KEY_FIELDS_JSON TEXT,
	CREATED_BY VARCHAR(128),
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_STANDARD_TEMPLATES PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX CAD_SW_LIBRARY.UK_STANDARD_TEMPLATES_CODE_VERSION
	ON CAD_SW_LIBRARY.STANDARD_TEMPLATES (TEMPLATE_CODE, TEMPLATE_VERSION);

CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_TEMPLATES_FAMILY
	ON CAD_SW_LIBRARY.STANDARD_TEMPLATES (FAMILY_CODE, IS_ACTIVE);

CREATE TABLE CAD_SW_LIBRARY.STANDARD_TEMPLATE_COLUMNS (
	ID BIGINT NOT NULL,
	TEMPLATE_ID BIGINT NOT NULL,
	FIELD_CODE VARCHAR(128) NOT NULL,
	FIELD_NAME VARCHAR(255) NOT NULL,
	DATA_TYPE VARCHAR(32) DEFAULT 'TEXT' NOT NULL,
	UNIT VARCHAR(32),
	IS_REQUIRED INT DEFAULT 0 NOT NULL,
	SORT_ORDER INT DEFAULT 0 NOT NULL,
	HEADER_ALIASES_JSON TEXT,
	VALIDATION_JSON TEXT,
	CONSTRAINT PK_STANDARD_TEMPLATE_COLUMNS PRIMARY KEY (ID),
	CONSTRAINT FK_STANDARD_TEMPLATE_COLUMNS_TEMPLATE FOREIGN KEY (TEMPLATE_ID)
		REFERENCES CAD_SW_LIBRARY.STANDARD_TEMPLATES(ID)
);

CREATE UNIQUE INDEX CAD_SW_LIBRARY.UK_STANDARD_TEMPLATE_COLUMNS_FIELD
	ON CAD_SW_LIBRARY.STANDARD_TEMPLATE_COLUMNS (TEMPLATE_ID, FIELD_CODE);

CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_TEMPLATE_COLUMNS_ORDER
	ON CAD_SW_LIBRARY.STANDARD_TEMPLATE_COLUMNS (TEMPLATE_ID, SORT_ORDER);

CREATE TABLE CAD_SW_LIBRARY.STANDARD_IMPORT_BATCHES (
	BATCH_ID VARCHAR(32) NOT NULL,
	SERIES_ID BIGINT NOT NULL,
	VERSION_ID BIGINT,
	TEMPLATE_ID BIGINT,
	FAMILY_CODE VARCHAR(64) NOT NULL,
	STATUS VARCHAR(32) DEFAULT 'PREVIEW' NOT NULL,
	ROW_COUNT INT DEFAULT 0 NOT NULL,
	ERROR_COUNT INT DEFAULT 0 NOT NULL,
	WARNING_COUNT INT DEFAULT 0 NOT NULL,
	UPDATE_STRATEGY VARCHAR(16) DEFAULT 'REPLACE' NOT NULL,
	DIFFERENCE_JSON TEXT,
	SOURCE_FILE_NAME VARCHAR(255),
	SOURCE_FILE_SHA256 VARCHAR(64),
	CREATED_BY VARCHAR(128),
	CREATED_AT TIMESTAMP NOT NULL,
	EXPIRES_AT TIMESTAMP,
	CONSTRAINT PK_STANDARD_IMPORT_BATCHES PRIMARY KEY (BATCH_ID),
	CONSTRAINT FK_STANDARD_IMPORT_BATCHES_SERIES FOREIGN KEY (SERIES_ID)
		REFERENCES CAD_SW_LIBRARY.STANDARD_SERIES(ID),
	CONSTRAINT FK_STANDARD_IMPORT_BATCHES_TEMPLATE FOREIGN KEY (TEMPLATE_ID)
		REFERENCES CAD_SW_LIBRARY.STANDARD_TEMPLATES(ID)
);

CREATE TABLE CAD_SW_LIBRARY.STANDARD_DYNAMIC_VERSION_ROWS (
	ROW_ID BIGINT NOT NULL,
	VERSION_ID BIGINT NOT NULL,
	ROW_NUMBER INT NOT NULL,
	UNIQUE_KEY_JSON TEXT,
	VALUES_JSON TEXT NOT NULL,
	SOURCE_BATCH_ID VARCHAR(32),
	CREATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_STANDARD_DYNAMIC_VERSION_ROWS PRIMARY KEY (ROW_ID),
	CONSTRAINT FK_STANDARD_DYNAMIC_VERSION_ROWS_VERSION FOREIGN KEY (VERSION_ID)
		REFERENCES CAD_SW_LIBRARY.STANDARD_DOCUMENT_VERSIONS(ID),
	CONSTRAINT FK_STANDARD_DYNAMIC_VERSION_ROWS_BATCH FOREIGN KEY (SOURCE_BATCH_ID)
		REFERENCES CAD_SW_LIBRARY.STANDARD_IMPORT_BATCHES(BATCH_ID)
);

CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_DYNAMIC_VERSION_ROWS_VERSION
	ON CAD_SW_LIBRARY.STANDARD_DYNAMIC_VERSION_ROWS (VERSION_ID);

CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_IMPORT_BATCHES_STATUS
	ON CAD_SW_LIBRARY.STANDARD_IMPORT_BATCHES (STATUS, EXPIRES_AT);

CREATE TABLE CAD_SW_LIBRARY.STANDARD_IMPORT_ROWS (
	ROW_ID BIGINT NOT NULL,
	BATCH_ID VARCHAR(32) NOT NULL,
	ROW_NUMBER INT NOT NULL,
	VALUES_JSON TEXT NOT NULL,
	ERRORS_JSON TEXT,
	WARNINGS_JSON TEXT,
	CREATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_STANDARD_IMPORT_ROWS PRIMARY KEY (ROW_ID),
	CONSTRAINT UK_STANDARD_IMPORT_ROWS_BATCH_ROW UNIQUE (BATCH_ID, ROW_NUMBER),
	CONSTRAINT FK_STANDARD_IMPORT_ROWS_BATCH FOREIGN KEY (BATCH_ID)
		REFERENCES CAD_SW_LIBRARY.STANDARD_IMPORT_BATCHES(BATCH_ID)
);
