-- 规范库基础表：达梦版本。
-- 固定目标库/Schema：CAD_SW_LIBRARY。
-- 本文件中的每一张表、约束和索引均使用 CAD_SW_LIBRARY 全限定名称。
-- 执行前请确认当前 DM 连接账号具有 CAD_SW_LIBRARY 下的建表、建约束和建索引权限。

CREATE TABLE CAD_SW_LIBRARY.STANDARD_FAMILIES (
	ID BIGINT NOT NULL,
	CODE VARCHAR(64) NOT NULL,
	NAME VARCHAR(128) NOT NULL,
	DESCRIPTION VARCHAR(500),
	IS_ACTIVE INT DEFAULT 1 NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_STANDARD_FAMILIES PRIMARY KEY (ID),
	CONSTRAINT UK_STANDARD_FAMILIES_CODE UNIQUE (CODE)
);

-- 基础规范号：同一个规范号可以包含多个细分规范系列。
CREATE TABLE CAD_SW_LIBRARY.STANDARD_DOCUMENTS (
	ID BIGINT NOT NULL,
	FAMILY_ID BIGINT NOT NULL,
	CATEGORY_ID BIGINT,
	STANDARD_NUMBER VARCHAR(100) NOT NULL,
	STANDARD_NAME VARCHAR(255),
	IS_ACTIVE INT DEFAULT 1 NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_STANDARD_DOCUMENTS PRIMARY KEY (ID),
	CONSTRAINT UK_STANDARD_DOCUMENTS_IDENTITY UNIQUE (FAMILY_ID, STANDARD_NUMBER),
	CONSTRAINT FK_STANDARD_DOCUMENTS_FAMILY FOREIGN KEY (FAMILY_ID)
		REFERENCES CAD_SW_LIBRARY.STANDARD_FAMILIES(ID)
);

CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_DOCUMENTS_NUMBER
	ON CAD_SW_LIBRARY.STANDARD_DOCUMENTS (STANDARD_NUMBER, IS_ACTIVE);

CREATE TABLE CAD_SW_LIBRARY.STANDARD_SERIES (
	ID BIGINT NOT NULL,
	FAMILY_ID BIGINT NOT NULL,
	STANDARD_DOCUMENT_ID BIGINT,
	SERIES_CODE VARCHAR(100) NOT NULL,
	SERIES_NAME VARCHAR(255) NOT NULL,
	STANDARD_NUMBER VARCHAR(100) NOT NULL,
	TABLE_NUMBER VARCHAR(64) NOT NULL,
	PRESSURE_RATING VARCHAR(64) NOT NULL,
	FLANGE_TYPE VARCHAR(64),
	FACE_TYPE VARCHAR(64),
	IS_ACTIVE INT DEFAULT 1 NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_STANDARD_SERIES PRIMARY KEY (ID),
	CONSTRAINT FK_STANDARD_SERIES_DOCUMENT FOREIGN KEY (STANDARD_DOCUMENT_ID)
		REFERENCES CAD_SW_LIBRARY.STANDARD_DOCUMENTS(ID),
	CONSTRAINT UK_STANDARD_SERIES_IDENTITY UNIQUE (FAMILY_ID, SERIES_CODE, STANDARD_NUMBER, TABLE_NUMBER, PRESSURE_RATING)
);

CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_SERIES_DOCUMENT
	ON CAD_SW_LIBRARY.STANDARD_SERIES (STANDARD_DOCUMENT_ID, IS_ACTIVE);

CREATE TABLE CAD_SW_LIBRARY.STANDARD_FLANGE_RECORDS (
	ID BIGINT NOT NULL,
	SERIES_ID BIGINT NOT NULL,
	SOURCE_ROW_NUMBER INT NOT NULL,
	DN VARCHAR(32) NOT NULL,
	DN_VALUE INT NOT NULL,
	PN VARCHAR(64) NOT NULL,
	PIPE_OUTER_DIAMETER_I DECIMAL(18,4),
	PIPE_OUTER_DIAMETER_II DECIMAL(18,4),
	FLANGE_OUTER_DIAMETER DECIMAL(18,4),
	BOLT_CIRCLE_DIAMETER DECIMAL(18,4),
	BOLT_HOLE_DIAMETER DECIMAL(18,4),
	BOLT_COUNT INT,
	BOLT_SPECIFICATION VARCHAR(64),
	BOLT_RAW_SUFFIX VARCHAR(128),
	FLANGE_THICKNESS DECIMAL(18,4),
	RAISED_FACE_HEIGHT DECIMAL(18,4),
	FLANGE_INNER_DIAMETER_I DECIMAL(18,4),
	FLANGE_INNER_DIAMETER_II DECIMAL(18,4),
	RAW_VALUES_JSON TEXT,
	WARNINGS_JSON TEXT,
	IS_ACTIVE INT DEFAULT 1 NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_STANDARD_FLANGE_RECORDS PRIMARY KEY (ID),
	CONSTRAINT UK_STANDARD_FLANGE_RECORD_IDENTITY UNIQUE (SERIES_ID, DN_VALUE, PN)
);

CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_SERIES_QUERY ON CAD_SW_LIBRARY.STANDARD_SERIES (SERIES_CODE, STANDARD_NUMBER, PRESSURE_RATING);
CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_FLANGE_RECORD_QUERY ON CAD_SW_LIBRARY.STANDARD_FLANGE_RECORDS (SERIES_ID, DN_VALUE, PN);
