-- 规范库基础表：达梦版本
-- 说明：执行账号需要具备在 CAD_SW_LIBRARY schema 下创建表、约束和索引的权限。
-- 说明：对象统一创建到服务配置中的 Database:Schema=CAD_SW_LIBRARY。

CREATE TABLE CAD_SW_LIBRARY.STANDARD_FAMILIES (
	ID BIGINT NOT NULL,
	CODE VARCHAR(64) NOT NULL,
	NAME VARCHAR(128) NOT NULL,
	DESCRIPTION VARCHAR(500),
	IS_ACTIVE INT DEFAULT 1 NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_STANDARD_FAMILIES PRIMARY KEY (ID),
	CONSTRAINT UK_STANDARD_FAMILIES_CODE UNIQUE (CODE)
);

CREATE TABLE CAD_SW_LIBRARY.STANDARD_SERIES (
	ID BIGINT NOT NULL,
	FAMILY_ID BIGINT NOT NULL,
	SERIES_CODE VARCHAR(100) NOT NULL,
	SERIES_NAME VARCHAR(255) NOT NULL,
	STANDARD_NUMBER VARCHAR(100) NOT NULL,
	TABLE_NUMBER VARCHAR(64) NOT NULL,
	PRESSURE_RATING VARCHAR(64) NOT NULL,
	FLANGE_TYPE VARCHAR(64),
	FACE_TYPE VARCHAR(64),
	IS_ACTIVE INT DEFAULT 1 NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_STANDARD_SERIES PRIMARY KEY (ID),
	CONSTRAINT UK_STANDARD_SERIES_IDENTITY UNIQUE (FAMILY_ID, SERIES_CODE, STANDARD_NUMBER, TABLE_NUMBER, PRESSURE_RATING)
);

CREATE TABLE CAD_SW_LIBRARY.STANDARD_FLANGE_RECORDS (
	ID BIGINT NOT NULL,
	SERIES_ID BIGINT NOT NULL,
	SOURCE_ROW_NUMBER INT NOT NULL,
	DN VARCHAR(32) NOT NULL,
	DN_VALUE INT NOT NULL,
	PN VARCHAR(64) NOT NULL,
	PIPE_OUTER_DIAMETER_I DECIMAL(18,4),
	PIPE_OUTER_DIAMETER_II DECIMAL(18,4),
	FLANGE_OUTER_DIAMETER DECIMAL(18,4),
	BOLT_CIRCLE_DIAMETER DECIMAL(18,4),
	BOLT_HOLE_DIAMETER DECIMAL(18,4),
	BOLT_COUNT INT,
	BOLT_SPECIFICATION VARCHAR(64),
	BOLT_RAW_SUFFIX VARCHAR(128),
	FLANGE_THICKNESS DECIMAL(18,4),
	RAISED_FACE_HEIGHT DECIMAL(18,4),
	FLANGE_INNER_DIAMETER_I DECIMAL(18,4),
	FLANGE_INNER_DIAMETER_II DECIMAL(18,4),
	RAW_VALUES_JSON TEXT,
	WARNINGS_JSON TEXT,
	IS_ACTIVE INT DEFAULT 1 NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_STANDARD_FLANGE_RECORDS PRIMARY KEY (ID),
	CONSTRAINT UK_STANDARD_FLANGE_RECORD_IDENTITY UNIQUE (SERIES_ID, DN_VALUE, PN)
);

CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_SERIES_QUERY ON CAD_SW_LIBRARY.STANDARD_SERIES (SERIES_CODE, STANDARD_NUMBER, PRESSURE_RATING);
CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_FLANGE_RECORD_QUERY ON CAD_SW_LIBRARY.STANDARD_FLANGE_RECORDS (SERIES_ID, DN_VALUE, PN);
