-- 动态规范导入结构升级脚本：达梦版本
-- 适用：已经执行过旧版 standard_template_schema_dm.sql 的数据库
-- 默认 Schema：CAD_SW_LIBRARY；如实际 Schema 不同，请先替换脚本中的 CAD_SW_LIBRARY。
-- 说明：脚本只增加动态导入所需字段和版本行表，不删除、不修改既有规范数据。
-- 执行账号需要 ALTER、CREATE TABLE、CREATE INDEX、REFERENCES 权限。

-- ============================================================
-- 1. 模板表增加来源文件名和唯一键字段
-- ============================================================
DECLARE
	V_COUNT INT;
BEGIN
	SELECT COUNT(1) INTO V_COUNT
	FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY'
	  AND TABLE_NAME = 'STANDARD_TEMPLATES'
	  AND COLUMN_NAME = 'SOURCE_FILE_NAME';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.STANDARD_TEMPLATES ADD SOURCE_FILE_NAME VARCHAR(255)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY'
	  AND TABLE_NAME = 'STANDARD_TEMPLATES'
	  AND COLUMN_NAME = 'UNIQUE_KEY_FIELDS_JSON';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.STANDARD_TEMPLATES ADD UNIQUE_KEY_FIELDS_JSON TEXT';
	END IF;
END;
/

-- ============================================================
-- 2. 批次表增加更新策略和差异摘要字段
-- ============================================================
DECLARE
	V_COUNT INT;
BEGIN
	SELECT COUNT(1) INTO V_COUNT
	FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY'
	  AND TABLE_NAME = 'STANDARD_IMPORT_BATCHES'
	  AND COLUMN_NAME = 'UPDATE_STRATEGY';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.STANDARD_IMPORT_BATCHES ADD UPDATE_STRATEGY VARCHAR(16) DEFAULT ''REPLACE'' NOT NULL';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY'
	  AND TABLE_NAME = 'STANDARD_IMPORT_BATCHES'
	  AND COLUMN_NAME = 'DIFFERENCE_JSON';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.STANDARD_IMPORT_BATCHES ADD DIFFERENCE_JSON TEXT';
	END IF;
END;
/

-- ============================================================
-- 3. 创建动态版本行表
-- ============================================================
DECLARE
	V_COUNT INT;
BEGIN
	SELECT COUNT(1) INTO V_COUNT
	FROM ALL_TABLES
	WHERE OWNER = 'CAD_SW_LIBRARY'
	  AND TABLE_NAME = 'STANDARD_DYNAMIC_VERSION_ROWS';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE '
CREATE TABLE CAD_SW_LIBRARY.STANDARD_DYNAMIC_VERSION_ROWS (
	ROW_ID BIGINT NOT NULL,
	VERSION_ID BIGINT NOT NULL,
	ROW_NUMBER INT NOT NULL,
	UNIQUE_KEY_JSON TEXT,
	VALUES_JSON TEXT NOT NULL,
	SOURCE_BATCH_ID VARCHAR(32),
	CREATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_STANDARD_DYNAMIC_VERSION_ROWS PRIMARY KEY (ROW_ID),
	CONSTRAINT FK_STANDARD_DYNAMIC_VERSION_ROWS_VERSION FOREIGN KEY (VERSION_ID)
		REFERENCES CAD_SW_LIBRARY.STANDARD_DOCUMENT_VERSIONS(ID),
	CONSTRAINT FK_STANDARD_DYNAMIC_VERSION_ROWS_BATCH FOREIGN KEY (SOURCE_BATCH_ID)
		REFERENCES CAD_SW_LIBRARY.STANDARD_IMPORT_BATCHES(BATCH_ID)
)';
	END IF;
END;
/

-- ============================================================
-- 4. 创建版本查询索引
-- ============================================================
DECLARE
	V_COUNT INT;
BEGIN
	SELECT COUNT(1) INTO V_COUNT
	FROM ALL_INDEXES
	WHERE OWNER = 'CAD_SW_LIBRARY'
	  AND INDEX_NAME = 'IX_STANDARD_DYNAMIC_VERSION_ROWS_VERSION';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_DYNAMIC_VERSION_ROWS_VERSION ON CAD_SW_LIBRARY.STANDARD_DYNAMIC_VERSION_ROWS (VERSION_ID)';
	END IF;
END;
/

-- ============================================================
-- 5. 升级结果检查
-- ============================================================
SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'CAD_SW_LIBRARY'
  AND (
		(TABLE_NAME = 'STANDARD_TEMPLATES' AND COLUMN_NAME IN ('SOURCE_FILE_NAME', 'UNIQUE_KEY_FIELDS_JSON'))
	 OR (TABLE_NAME = 'STANDARD_IMPORT_BATCHES' AND COLUMN_NAME IN ('UPDATE_STRATEGY', 'DIFFERENCE_JSON'))
  )
ORDER BY TABLE_NAME, COLUMN_NAME;

SELECT OWNER, TABLE_NAME
FROM ALL_TABLES
WHERE OWNER = 'CAD_SW_LIBRARY'
  AND TABLE_NAME = 'STANDARD_DYNAMIC_VERSION_ROWS';

SELECT OWNER, INDEX_NAME, TABLE_NAME
FROM ALL_INDEXES
WHERE OWNER = 'CAD_SW_LIBRARY'
  AND INDEX_NAME = 'IX_STANDARD_DYNAMIC_VERSION_ROWS_VERSION';
