-- 基础规范号层级升级脚本。
-- 目标库：CAD_SW_LIBRARY。
-- 适用于已经执行旧版 standard_schema_dm.sql 的测试库。
-- 执行前请确认当前数据库连接账号具有建表、建约束、建索引和修改表权限。

-- 1. 创建基础规范号表。
CREATE TABLE CAD_SW_LIBRARY.STANDARD_DOCUMENTS (
	ID BIGINT NOT NULL,
	FAMILY_ID BIGINT NOT NULL,
	CATEGORY_ID BIGINT,
	STANDARD_NUMBER VARCHAR(100) NOT NULL,
	STANDARD_NAME VARCHAR(255),
	IS_ACTIVE INT DEFAULT 1 NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_STANDARD_DOCUMENTS PRIMARY KEY (ID),
	CONSTRAINT UK_STANDARD_DOCUMENTS_IDENTITY UNIQUE (FAMILY_ID, STANDARD_NUMBER),
	CONSTRAINT FK_STANDARD_DOCUMENTS_FAMILY FOREIGN KEY (FAMILY_ID)
		REFERENCES CAD_SW_LIBRARY.STANDARD_FAMILIES(ID)
);

-- 2. 为细分规范系列增加基础规范号外键。
ALTER TABLE CAD_SW_LIBRARY.STANDARD_SERIES ADD STANDARD_DOCUMENT_ID BIGINT;

ALTER TABLE CAD_SW_LIBRARY.STANDARD_SERIES ADD CONSTRAINT FK_STANDARD_SERIES_DOCUMENT
	FOREIGN KEY (STANDARD_DOCUMENT_ID)
	REFERENCES CAD_SW_LIBRARY.STANDARD_DOCUMENTS(ID);

CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_DOCUMENTS_NUMBER
	ON CAD_SW_LIBRARY.STANDARD_DOCUMENTS (STANDARD_NUMBER, IS_ACTIVE);

CREATE INDEX CAD_SW_LIBRARY.IX_STANDARD_SERIES_DOCUMENT
	ON CAD_SW_LIBRARY.STANDARD_SERIES (STANDARD_DOCUMENT_ID, IS_ACTIVE);

-- 3. 从现有系列数据生成基础规范号记录。
-- 同一专业、同一规范号只生成一条基础规范号。
INSERT INTO CAD_SW_LIBRARY.STANDARD_DOCUMENTS
	(ID, FAMILY_ID, CATEGORY_ID, STANDARD_NUMBER, STANDARD_NAME, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT
	ROW_NUMBER() OVER (ORDER BY ss.FAMILY_ID, TRIM(ss.STANDARD_NUMBER)) +
		COALESCE((SELECT MAX(ID) FROM CAD_SW_LIBRARY.STANDARD_DOCUMENTS), 0),
	ss.FAMILY_ID,
	MIN(ss.CATEGORY_ID),
	TRIM(ss.STANDARD_NUMBER),
	MIN(ss.STANDARD_NUMBER),
	1,
	CURRENT_TIMESTAMP,
	CURRENT_TIMESTAMP
FROM CAD_SW_LIBRARY.STANDARD_SERIES ss
WHERE ss.IS_ACTIVE = 1
  AND TRIM(COALESCE(ss.STANDARD_NUMBER, '')) <> ''
GROUP BY ss.FAMILY_ID, TRIM(ss.STANDARD_NUMBER);

-- 4. 将已有细分系列挂接到基础规范号。
UPDATE CAD_SW_LIBRARY.STANDARD_SERIES ss
SET STANDARD_DOCUMENT_ID = (
	SELECT sd.ID
	FROM CAD_SW_LIBRARY.STANDARD_DOCUMENTS sd
	WHERE sd.FAMILY_ID = ss.FAMILY_ID
	  AND sd.STANDARD_NUMBER = TRIM(ss.STANDARD_NUMBER)
	  AND sd.IS_ACTIVE = 1
)
WHERE ss.IS_ACTIVE = 1
  AND STANDARD_DOCUMENT_ID IS NULL;

-- 5. 检查迁移结果。
SELECT COUNT(*) AS DOCUMENT_COUNT
FROM CAD_SW_LIBRARY.STANDARD_DOCUMENTS;

SELECT COUNT(*) AS UNLINKED_SERIES_COUNT
FROM CAD_SW_LIBRARY.STANDARD_SERIES
WHERE IS_ACTIVE = 1 AND STANDARD_DOCUMENT_ID IS NULL;

SELECT sd.STANDARD_NUMBER, COUNT(ss.ID) AS SERIES_COUNT
FROM CAD_SW_LIBRARY.STANDARD_DOCUMENTS sd
LEFT JOIN CAD_SW_LIBRARY.STANDARD_SERIES ss
	ON ss.STANDARD_DOCUMENT_ID = sd.ID AND ss.IS_ACTIVE = 1
GROUP BY sd.STANDARD_NUMBER
ORDER BY sd.STANDARD_NUMBER;
